# Owner of the GitHub repository
owner: SRESchool

# Name of the GitHub repository
repo: All-HolidayLandmark-Websites-Uptime-Monitor

user-agent: pritesh-1904
skipReadme: true
skipDescription: true
skipTopics: true

# List of websites to monitor for uptime and SSL
sites:
  - name: Bangalore Orbit
    url: https://bangaloreorbit.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Bhopal Orbit
    url: https://bhopalorbit.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Gujarat Orbit
    url: https://gujaratorbit.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Chennai Orbit
    url: https://chennaiorbit.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Holiday Landmark
    url: https://holidaylandmark.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Kerala Orbit
    url: https://keralaorbit.in
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Mera Apna Bihar
    url: https://meraapnabihar.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Mumbai Orbit
    url: https://mumbaiorbit.in
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
    
status-website:
  cname: null
  baseUrl: /All-HolidayLandmark-Websites-Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: All Holiday Landmark Websites Uptime Monitor
  introTitle: Holiday Landmark Websites Status
  introMessage: This page shows the uptime and SSL status of Holiday Landmark Websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.ico
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Workflow schedule (every 5 minutes)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
  ssl: "*/5 * * * *"

# Committer configuration
committer:
  name: Pritesh
  email: contact@motoshare.in

# Email notification configuration
notifications:
  - type: email
    smtpTo: contact@motoshare.in
    smtpFrom: pritesh.cotocus@gmail.com
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: "kmxg nshc vsrf kxqj"
    events:
      - up
      - down

# Assignees for issues
assignees:
  - pritesh-1904
